name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]


    steps:
    - uses: actions/checkout@v2
    - name: install conan
      run:  pip3 install conan
    - name: create build folder
      run: mkdir build
    - name: install dependencies
      working-directory: ./build
      run: conan install .. --build=missing
    - name: generate
      working-directory: ./build
      run: cmake ..
    - name: build
      working-directory: ./build
      run: cmake --build .
    - name: fix executable name
      run: mv ./build/bin/ColodexTest* ./ColodexTest.exe
    - name: run tests
      env:
        HOLODEX_TOKEN: ${{ secrets.HOLODEX_TOKEN }}
      run: ./ColodexTest.exe
